class Buffer
  @cursor: Hash[Symbol, Integer]
  @lines: Array[String]

  def initialize: (?String prompt) -> void
  def cursor: () -> Hash[Symbol, Integer]
  def clear: () -> void
  def dump: () -> void
  def home: () -> void
  def head: () -> void
  def tail: () -> void
  def left: () -> void
  def right: () -> void
  def up: () -> void
  def down: () -> void
  def put: (String) -> void
end

