
class Debouncer
  DEBOUNCE_TYPES: Array[Symbol]
  DEFAULT_THRESHOLD: Integer

  @pk_table: Hash[Integer, { pin_val: bool, time: Integer }]
  @now: Integer
  @threshold: Integer
  @type: Symbol

  def initialize: (?Symbol `type_val`) -> void
  def resolve: (bool pin_val, Integer row, Integer col) -> bool
  def type=: (Symbol) -> void
  def threshold=: (Integer) -> void
  def set_time: () -> void
end
