class Joystick
  VALID_PINS: Array[Integer]

  def initialize: (Hash[Symbol, Integer]) -> void
  def reset_axes: () -> nil
  def init_axis_offset: (String axis, Integer pin) -> bool
  def set_values: (Integer, Integer) -> nil
end
