# TypeProf 0.14.1

# Global variables
$mutex: bool

# Classes
class Object
end

class Keyboard
  GPIO_IN: Integer
  GPIO_IN_PULLUP: Integer
  GPIO_IN_PULLDOWN: Integer
  GPIO_OUT: Integer
  GPIO_OUT_LO: Integer
  GPIO_OUT_HI: Integer

  MOD_KEYCODE: Hash[Symbol, Integer]
  KEYCODE: Array[Symbol]
  KEYCODE_SFT: Hash[Symbol, Integer]
  KEYCODE_RGB: Hash[Symbol, Integer]
  LETTER: Array[String | Symbol | nil]
  KC_ALIASES: Hash[Symbol, Symbol]

  STANDARD_SPLIT: Symbol
  RIGHT_SIDE_FLIPPED_SPLIT: Symbol

  @SHIFT_LETTER_OFFSET_A: Integer
  @SHIFT_LETTER_OFFSET_UNDS: Integer
  @SHIFT_LETTER_THRESHOLD_A: Integer
  @SHIFT_LETTER_THRESHOLD_UNDS: Integer

  @before_filters: Array[^() -> void]
  @keymaps: Hash[Symbol, Array[Array[Integer | Symbol | Proc]]]
  @mode_keys: Array[{
    layer:             Symbol,
    on_release:        Integer | Array[Integer] | Proc | nil,
    on_hold:           Integer | Symbol | Proc,
    release_threshold: Integer,
    repush_threshold:  Integer,
    switch:            [Integer, Integer],
    prev_state:        Symbol,
    pushed_at:         Integer,
    released_at:       Integer
    }
    ]
  @switches: Array[Array[Integer]]
  @layer_names: Array[Symbol]
  @layer: Symbol
  @anchor: bool
  @anchor_left: bool
  @direct_pins: Array[Integer]
  @rows_size: Integer
  @cols_size: Integer
  @matrix: Hash[Integer, Hash[Integer, Array[Integer]]]
  @locked_layer: Symbol | nil
  @keycodes: Array[String]
  @macro_keys: Array[Integer]
  @macro_key_numbers: Array[Integer | nil]
  @modifier: Integer
  @split_style: Symbol
  @message: Integer
  @encoders: Array[RotaryEncoder]
  @scan_mode: Symbol

  attr_accessor split: bool
  attr_accessor uart_pin: Integer

  def append: (RGB | RotaryEncoder feature) -> void
  def start_features: -> void
  def mutual_uart_at_my_own_risk= : (bool) -> void
  def uart_partner_push8 : (Integer) -> void
  def uart_partner : () -> Integer
  def uart_anchor : (Integer) -> Integer
  def uart_anchor_init : (Integer) -> void
  def uart_partner_init : (Integer) -> void
  def report_hid : (Integer, String) -> void
  def initialize: -> void
  def layer: () -> Symbol
  def set_anchor: (Symbol val) -> void
  def set_scan_mode: (Symbol val) -> void
  def split_style=: (Symbol style) -> void
  def init_matrix_pins: (Array[Array[Integer]] matrix) -> void
  def init_uart: () -> void
  def init_pins: (Array[Integer] rows, Array[Integer] cols) -> void
  def init_direct_pins: (Array[Integer] pins) -> void
  def add_layer: (Symbol name, Array[Symbol] map) -> void
  def calculate_col_position: (Integer col_index, Integer entire_cols_size) -> Integer
  def find_keycode_index: (Symbol key) -> (Integer | Symbol)
  def define_mode_key: (Symbol key_name, [Symbol | Array[Symbol] | Proc | nil, Symbol | Proc, Integer?, Integer?] param) -> void
  def invert_sft: -> void
  def before_report: () { () -> void } -> void
  def keys_include?: (Symbol) -> bool
  def action_on_release: (Integer | Array[Integer] | Proc | nil) -> void
  def action_on_hold: (Integer | Symbol | Proc) -> void
  def send_key: (Symbol) -> void
  def start!: -> void
  def raise_layer: -> void
  def lower_layer: -> void
  def lock_layer: (Symbol layer_name) -> void
  def unlock_layer: () -> void
  def macro: (String text, ?::Array[Symbol] opt) -> void
  def eval: (String) -> void
  def ruby: () -> void
  def scan_matrix!: () -> Array[Array[Integer]]
  def scan_direct!: () -> Array[Array[Integer]]
end
