# TypeProf 0.14.1

# Global variables
$rgb: RGB

# Classes
class RGB
  def ws2812_init: (Integer, Integer, bool) -> void
  def ws2812_off: () -> void
  def ws2812_show: () -> void
  def ws2812_fill: (Integer) -> void
  def ws2812_rand_fill: (Integer, Integer) -> void
  def ws2812_set_pixel_at: (Integer, Integer) -> void
  def ws2812_rotate: () -> void
  def ws2812_save: () -> void
  def ws2812_restore: () -> void

  @fifo: Array[true]
  @effect: Symbol
  @action: Symbol
  @delay: Integer
  @pixel_size: Integer
  @value: Integer
  @max_value: Integer
  @hue: Integer

  def hsv2rgb: (Float | Integer h, Integer s, Float | Integer v) -> Integer

  def initialize: (Integer pin, Integer underglow_size, Integer backlight_size, ?bool is_rgbw) -> void
  attr_reader pixel_size: Integer
  attr_reader delay: Integer
  attr_reader effect: Symbol
  attr_accessor action: Symbol
  def turn_off: () -> void
  def toggle: () -> void
  def effect=: (Symbol) -> void
  def reset_pixel: () -> void
  def invoke_anchor: (Symbol | nil) -> Integer
  def invoke_partner: (Integer) -> void
  def show: -> void
  def fifo_push: (true data) -> void
  def thunder: -> void
end
