# TypeProf 0.14.1

# Global variables
$rgb: RGB

# Classes
class RGB
  EFFECTS: Array[Symbol]

  def ws2812_init: (Integer, Integer, bool) -> void
  def ws2812_show: () -> void
  def ws2812_fill: (Integer, Integer) -> void
  def ws2812_rand_show: (Integer, Integer, Integer) -> void
  def ws2812_set_pixel_at: (Integer, Integer) -> void
  def ws2812_rotate_swirl: (Integer) -> bool
  def ws2812_reset_swirl_index: () -> bool

  @fifo: Array[true]
  @effect: Symbol
  @action: Symbol
  @speed: Integer
  @delay: Integer
  @pixel_size: Integer
  @max_value: Integer
  @value: Float
  @hue: Integer

  def hsv2rgb: (Float | Integer h, Integer s, Float | Integer v) -> Integer

  attr_reader pixel_size: Integer
  attr_reader effect: Symbol
  attr_accessor action: Symbol
  attr_accessor anchor: bool

  def initialize: (Integer pin, Integer underglow_size, Integer backlight_size, ?bool is_rgbw) -> void
  def init_values: () -> void
  def turn_off: () -> void
  def turn_on: () -> void
  def toggle: () -> void
  def effect=: (Symbol) -> void
  def hue=: (Integer) -> void
  def saturation=: (Integer) -> void
  def value=: (Integer) -> void
  def speed=: (Integer) -> void
  def reset_pixel: () -> void
  def invoke_anchor: (Symbol | nil) -> Integer
  def invoke_partner: (Integer) -> void
  def show: -> void
  def fifo_push: (true data) -> void
  def thunder: -> void
  def ping: () -> void
end
