class RotaryEncoder
  @proc_cw: ^() -> void
  @proc_ccw: ^() -> void

  def init_encoder: (Integer, Integer) -> void
  def read_encoder: () -> Integer
  def encoder_value: () -> Integer
  def reset_encoder: () -> void

  def initialize: (Integer pin_a, Integer pin_b) -> void
  def clockwise: () { () -> void } -> void
  def counterclockwise: () { () -> void } -> void
  def consume_rotation: () -> void
end
