class Sounder
  PRESET_SONGS: Hash[Symbol, String]

  attr_accessor playing: bool

  def sounder_init: (Integer) -> void
  def sounder_replay: () -> void

  def replay: () -> void
  def play: (*String) -> void
  def set_song: (*String) -> void
  def initialize: (Integer) -> void
  def add_note: (Integer frequency, Integer duration) -> bool
  def clear_song: () -> void
  def replay_if_key_pressed: () -> void
end
