task :steep do
  require "steep"
  require "steep/cli"
  res = Steep::CLI.new(argv: ["check", "--log-level=error"], stdout: $stdout, stderr: $stderr, stdin: $stdin).run
  raise "Steep check failed!" if res > 0
end

namespace :steep do
  task :check do
    sh %q(bundle exec steep check)
  end
  task :stats do
    sh %q(bundle exec steep stats --log-level=error --format=table)
  end
  task :watch do
    sh %q(bundle exec steep watch lib sig)
  end
end

task :test do
  sh %q(RUBYLIB=./app/models CFLAGS=-DMAX_SYMBOLS_COUNT=1000 bundle exec mrubyc-test)
end
