#ifndef RAW_HID_H_
#define RAW_HID_H_

#include "hid.h"

#define REPORT_RAW_MAX_LEN 0x20
#define RAW_HID_REPORT_DESC(...) \
    HID_USAGE_PAGE_N(0xFF60,2),\
    HID_USAGE(0x61), \
    HID_COLLECTION(HID_COLLECTION_APPLICATION), \
    __VA_ARGS__ \
    HID_USAGE(0x62), \
    HID_LOGICAL_MIN(0), \
    HID_LOGICAL_MAX_N(0x00FF, 2), \
    HID_REPORT_COUNT(REPORT_RAW_MAX_LEN), \
    HID_REPORT_SIZE(8), \
    HID_INPUT( HID_DATA | HID_VARIABLE | HID_ABSOLUTE), \
    \
    HID_USAGE(0x63), \
    HID_LOGICAL_MIN(0), \
    HID_LOGICAL_MAX_N(0x00FF, 2), \
    HID_REPORT_COUNT(REPORT_RAW_MAX_LEN), \
    HID_REPORT_SIZE(8), \
    HID_OUTPUT( HID_DATA | HID_VARIABLE | HID_ABSOLUTE | HID_VOLATILE), \
    HID_COLLECTION_END

#endif